drop table RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc 
drop table #SV_WD_RAN_AN_LIST

SELECT DISTINCT ROOT_ACCOUNT_NUMBER
INTO #SV_WD_RAN_AN_LIST
FROM externaluser.[SingleView].[GLDetail_Data_Monthly_Enhanced] as sv  
WHERE (CUSTOMER_DIVISION ='WEST' OR SERVICE_A_DIVISION='WEST' OR SERVICE_A_DIVISION ='WEST') AND amount <> 0 and CHARGE_TYPE = 'RC'and PRODUCT_INSTANCE_STATUS = 'Active'
--- DROP INDEX ix_SV_WD_RAN_AN_LIST ON #SV_WD_RAN_AN_LIST 
CREATE CLUSTERED INDEX ix_SV_WD_RAN_AN_LIST ON #SV_WD_RAN_AN_LIST (ROOT_ACCOUNT_NUMBER)--- 38549 --- 38511 IF NOT USING SITES AS WELL



DECLARE @VLOOKUP_TABLE TABLE (LOOKUP_WORD VARCHAR(250),RETURN_VALUE VARCHAR(50))
INSERT INTO @VLOOKUP_TABLE 
------------------AGGREGATOR ITEMS HERE
VALUES('BHI','AGGREGATOR'), ('Cicat','AGGREGATOR'), ('DSR','AGGREGATOR'), ('Granite','AGGREGATOR'), ('Hughes','AGGREGATOR'), ('ipass','AGGREGATOR'), ('Megapath','AGGREGATOR'), ('Netwolves','AGGREGATOR'), ('New Edge','AGGREGATOR'), ('CENIC','AGGREGATOR')
------------------NATIONAL ITEMS HERE
,('24 Hour Fitness','NATIONAL'),  ('7 eleven ','NATIONAL'),  ('7-eleven','NATIONAL'),  ('Ace Hardware','NATIONAL'),  ('Aetna','NATIONAL'),  ('Allen Alliance','NATIONAL'),  ('Amazon','NATIONAL'),  ('Apple Inc','NATIONAL'),  ('Argos','NATIONAL'),  ('Best Western ','NATIONAL'),  ('BHI','NATIONAL'),  ('Burger King','NATIONAL'),  ('Chick-fil-a','NATIONAL'),  ('Cicat','NATIONAL'),  ('Cigna','NATIONAL'),  ('Connecticut Insurance','NATIONAL'),  ('Davita ','NATIONAL'),  ('Dolex','NATIONAL'),  
('Dominos ','NATIONAL'),  ('DSR','NATIONAL'),  ('Edward Jones','NATIONAL'),  ('Farmers Insurance','NATIONAL'),  ('FedEx','NATIONAL'),  ('Fidelity ','NATIONAL'),  ('Google','NATIONAL'),  ('Granite','NATIONAL'),  ('Hilton ','NATIONAL'),  ('Hughes ','NATIONAL'),  ('ipass','NATIONAL'),  ('Jack in the box ','NATIONAL'),  ('Little Caesars','NATIONAL'),  ('Marriott','NATIONAL'),  ('Mc Donalds','NATIONAL'),  ('McDonalds ','NATIONAL'),   ('NAH Program','NATIONAL'),  ('National','NATIONAL'),  
('-National ','NATIONAL'),  ('Netwolves ','NATIONAL'),  ('New Edge ','NATIONAL'),  ('Noodles ','NATIONAL'),  ('Papa Murphy','NATIONAL'),  ('Peet''s Coffee','NATIONAL'),  ('Pet Smart','NATIONAL'),  ('Petco ','NATIONAL'),  ('PetSmart','NATIONAL'),  ('Pizza Hut','NATIONAL'),  ('Starbucks Level3','NATIONAL'),  ('State Farm ','NATIONAL'),  ('Taco Bell','NATIONAL'),  ('Teleworker','NATIONAL'),  
('TLWK','NATIONAL'),  ('TLWKR','NATIONAL'),  ('Tmobile','NATIONAL'),  ('Meijer, Inc.','NATIONAL'), ('KROGER','NATIONAL'),  ('T-mobile ','NATIONAL'),  ('TWK','NATIONAL'),  ('UHC','NATIONAL'),  ('UHG','NATIONAL'),  ('United Healthcare','NATIONAL'),  ('UNITED SERVICE AUTOMOBILE ASSOCIATION (USAA)','NATIONAL'),  ('UPS Store ','NATIONAL'),  ('Wingstop ','NATIONAL')
------------------CARRIER ITEMS DRAWN FROM SV_PLR HERE
INSERT INTO @VLOOKUP_TABLE  SELECT DISTINCT ROOT_CUSTOMER_NAME LOOKUP_WORD, 'CARRIER' RETURN_VALUE 
							FROM [ExternalUser].[SingleView].[Product_Local_Recon] as S 
							WHERE 
							(GENERAL_4_Value LIKE '%CARRIER%' OR Sales_Channel = '28 - Carrier')  AND	
							ROOT_CUSTOMER_NAME NOT IN ('CalNet')  AND 	
							GENERAL_4_Label = 'Line of Business' AND service_status_desc <> 'Cancelled' AND Child_Account_CustomerNodeStatus = 'Active'

----------------------------------------------------------------------------------------------------------------
------------LOAD TABLE WITH ACCOUNTS GROUPED TO = ROOT, ACCOUNT, NODE, GEOCODE LOCATION IDENTIFIER SET ---------
----------------------------------------------------------------------------------------------------------------
IF EXISTS( SELECT * FROM sys.objects WHERE [NAME] ='SCA_MODULE_STAGE1sv_biller_mrc_loc' ) DROP TABLE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc;
--  DROP TABLE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc
SELECT 
SV.ROOT_ACCOUNT_NUMBER,max(CASE WHEN CUSTOMER_DIVISION ='WEST' THEN 'Y' ELSE 'N' END) SV_WD_ROOT_CUSTOMER,
ROOT_CUSTOMER_NAME,INVOICE_ACCOUNT_NAME, ------  max(CUSTOMER_LINE_1) SV_ROOT_ADDR1,MAX(CUSTOMER_LINE_2) SV_ROOT_ADDR2,MAX(CUSTOMER_CITY) SV_ROOT_CITY,MAX(LEFT(CUSTOMER_STATE,2)) SV_ROOT_STATE,MAX(CUSTOMER_ZIP) SV_ROOT_ZIP,
HIERARCHY_LEVEL,ACCT_NUM,NODE_NAME, PRODUCT_INSTANCE_ID
,AAN,left(REPLACE(AAN,'''',''),16) AANCUT,
CASE WHEN left(REPLACE(AAN,'''',''),1) = '8' THEN left(REPLACE(AAN,'''',''),4) WHEN left(REPLACE(AAN,'''',''),1) <> '8' THEN 'XCSG' ELSE NULL END AAN4,
max(CASE WHEN (SERVICE_A_DIVISION='WEST' OR SERVICE_A_DIVISION ='WEST') THEN 'Y' ELSE 'N' END) SV_WD_SITE,
SERVICE_A_GEOCODE,CONCAT(SV.ROOT_ACCOUNT_NUMBER,ACCT_NUM ,SERVICE_A_GEOCODE) DISTINCT_LOC_ID,   ----------------------------REVIEWED TO IDENTIFY THIS AS A SUFFICIENT LOCATION IDENTIFIER
max(SERVICE_A_LINE_1) SV_ACCT_ADDR1,MAX(SERVICE_A_LINE_2) SV_ACCT_ADDR2,MAX(SERVICE_A_CITY) SV_ACCT_CITY,MAX(LEFT(SERVICE_A_STATE,2)) SV_ACCT_STATE,MAX(SERVICE_A_ZIP) SV_ACCT_ZIP,
sum(Amount) SV_MRC_TOTAL,
sum(case when SV_LINE_OF_BUSINESS like 'ME%' then Amount else 0 end) SV_MRC_METROE,
sum(case when SV_LINE_OF_BUSINESS = 'Advance Voice' AND Entry_Name_2 like '%PRI%' AND Entry_Name_2 NOT like '%PRIVATE%' then Amount else 0 end) SV_MRCsubset_AV_PRI,
sum(case when SV_LINE_OF_BUSINESS = 'Advance Voice' AND (Entry_Name_2 like '%SIP%' OR Entry_Name_1 like '%SIP%')then Amount else 0 end) SV_MRCsubset_AV_SIP,
sum(case when SV_LINE_OF_BUSINESS = 'Advance Voice' AND Entry_Name_1 like '%bve%' then Amount else 0 end) SV_MRCsubset_AV_BVE,
sum(case when SV_LINE_OF_BUSINESS = 'Advance Voice' then Amount else 0 end) SV_MRC_AV_TOTAL,
sum(case when SV_LINE_OF_BUSINESS = 'Managed Services' then Amount else 0 end) MES$Amount,
sum(case when SV_LINE_OF_BUSINESS = 'Carrier' then Amount 
	 WHEN RETURN_VALUE = 'CARRIER' THEN Amount else 0 end) Carrier$Amount,
sum(case WHEN ROOT_CUSTOMER_NAME LIKE '%CBH%' THEN Amount
		when SV_LINE_OF_BUSINESS = 'CBH' then Amount else 0 end) CBH$Amount,
sum(case when SV_LINE_OF_BUSINESS = 'National' then Amount 
		  WHEN SALES_CHANNEL LIKE '%- National%' THEN Amount 
		  WHEN VL.RETURN_VALUE = 'NATIONAL' THEN Amount else 0 end) National$Amount,
sum(case when SV_LINE_OF_BUSINESS = 'National' and Entry_Name_1 =  'Broadband Commuter Service' then Amount else 0 end) National_TW$Amount,
MAX(CASE WHEN SV_LINE_OF_BUSINESS IN ('National') THEN 'Y'
		  WHEN SALES_CHANNEL LIKE '%- National%' THEN 'Y' 
		  WHEN VL.RETURN_VALUE = 'NATIONAL' THEN 'Y' ELSE NULL END) NAT_IND,
MAX(CASE WHEN SV_LINE_OF_BUSINESS LIKE '%GOVERNMENT%' THEN 'Y'
		WHEN ROOT_CUSTOMER_NAME LIKE '%GOVERNMENT%' THEN 'Y'
		WHEN SALES_CHANNEL = '27 - GEM'  THEN 'Y' ELSE NULL END) GOV_IND,
MAX(CASE WHEN NODE_NAME LIKE '%School%' THEN 'Y'
		WHEN ROOT_CUSTOMER_NAME LIKE '%EDUCATION%' THEN 'Y'
		WHEN ROOT_CUSTOMER_NAME LIKE '%COLLEGE%' THEN 'Y'
		WHEN ROOT_CUSTOMER_NAME LIKE '%UNIVERSITY%' THEN 'Y' ELSE NULL END) EDU_IND,
MAX(CASE WHEN SERVICE_PROVIDER = 'Aggregator' THEN 'Y'
	  WHEN VL.RETURN_VALUE = 'AGGREGATOR' THEN 'Y' ELSE NULL END) AGGR_IND,
MAX(CASE WHEN SV_LINE_OF_BUSINESS like 'Managed%Service%' THEN 'Y' ELSE NULL END) MES_IND,
MAX(CASE WHEN SV_LINE_OF_BUSINESS = 'Carrier' THEN 'Y' 
	 WHEN RETURN_VALUE = 'CARRIER' THEN  'Y' ELSE NULL END) CAR_IND,
MAX(CASE WHEN ROOT_CUSTOMER_NAME LIKE '%CBH%' THEN 'Y'
		WHEN SV_LINE_OF_BUSINESS LIKE '%CBH%' THEN 'Y' ELSE NULL END) CBH_IND,
MAX(CASE WHEN SV_LINE_OF_BUSINESS LIKE '%Hospitality%' THEN 'Y' ELSE NULL END) HSPY_IND,
MAX(CASE WHEN SV_LINE_OF_BUSINESS = 'Broadband Commuter Service' then 'Y'
	WHEN ROOT_CUSTOMER_NAME LIKE '%Teleworker%' THEN 'Y' ELSE NULL END) TWKR_IND,
	GETDATE() LOAD_DT
INTO RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc --- 530058 rows ---- was 523941 rows when not including lots  --- select distinct SV_LINE_OF_BUSINESS
from --   SELECT DISTINCT ROOT_ACCOUNT_NUMBER,ACCT_NUM,NODE_NAME,CUSTOMER_LINE_1,SERVICE_A_SITE_NAME,SERVICE_B_SITE_NAME,SERVICE_A_LINE_1 FROM
externaluser.[SingleView].[GLDetail_Data_Monthly_Enhanced] as sv  -----------------WHERE CUSTOMER_DIVISION = 'WEST' AND ROOT_ACCOUNT_NUMBER IN ('962634163','904971899','908349621') ORDER BY 2,ACCT_NUM ,SERVICE_A_GEOCODE , CUSTOMER_NODE_ID,NODE_NAME,[SERVICE_NAME]
JOIN  #SV_WD_RAN_AN_LIST AS WD ON WD.ROOT_ACCOUNT_NUMBER = SV.ROOT_ACCOUNT_NUMBER
LEFT JOIN @VLOOKUP_TABLE AS VL
ON ROOT_CUSTOMER_NAME LIKE '%'+VL.LOOKUP_WORD+'%'
WHERE AMOUNT <> 0 and CHARGE_TYPE = 'RC'and PRODUCT_INSTANCE_STATUS = 'Active'
group by SV.ROOT_ACCOUNT_NUMBER,ROOT_CUSTOMER_NAME,INVOICE_ACCOUNT_NAME,
HIERARCHY_LEVEL,ACCT_NUM,SERVICE_A_GEOCODE,AAN,NODE_NAME, PRODUCT_INSTANCE_ID
----------------rows 357078 in 4min 38sec -- 5min 58sec

CREATE NONCLUSTERED INDEX ix_SCA_MODULE_STAGE1sv_biller_mrc_loc1 ON RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc(ROOT_ACCOUNT_NUMBER,ACCT_NUM,AANCUT) 
--CREATE CLUSTERED INDEX ix_SCA_MODULE_STAGE1sv_biller_mrc_loc2 ON RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc(AAN4,SV_EXCL_IND) 


ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc ADD SV_EXCL_IND VARCHAR(1); 
update a SET SV_EXCL_IND  = CASE WHEN COALESCE(NAT_IND,GOV_IND,EDU_IND,AGGR_IND,MES_IND,CAR_IND,CBH_IND,TWKR_IND) IS NOT NULL THEN 'Y' ELSE NULL END
from RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc as a 


SELECT
	*
INTO RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao
FROM
(
SELECT 
	ROOT_ACCOUNT_NUMBER	
	,SV_WD_ROOT_CUSTOMER	
	,ROOT_CUSTOMER_NAME	
	,INVOICE_ACCOUNT_NAME	
	,HIERARCHY_LEVEL	
	,ACCT_NUM	
	,NODE_NAME	
	,PRODUCT_INSTANCE_ID
	,AAN	
	,AANCUT	
	,AAN4	
	,SV_WD_SITE	
	,SERVICE_A_GEOCODE	
	,DISTINCT_LOC_ID	
	,SV_ACCT_ADDR1	
	,SV_ACCT_ADDR2	
	,SV_ACCT_CITY	
	,SV_ACCT_STATE	
	,SV_ACCT_ZIP	
	,NAT_IND
	,GOV_IND	
	,EDU_IND	
	,AGGR_IND	
	,MES_IND	
	,CAR_IND	
	,CBH_IND
	,HSPY_IND
	,TWKR_IND	
	,LOAD_DT	
	,SV_EXCL_IND
	,ROW_NUMBER() OVER (PARTITION BY  distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2	order by product_instance_id) as rnk
	,sum(SV_MRC_TOTAL) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRC_TOTAL
	,sum(SV_MRC_METROE) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRC_METROE
	,sum(SV_MRCsubset_AV_PRI) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRCsubset_AV_PRI
	,sum(SV_MRCsubset_AV_SIP) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRCsubset_AV_SIP
	,sum(SV_MRCsubset_AV_BVE) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRCsubset_AV_BVE
	,sum(SV_MRC_AV_TOTAL) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) SV_MRC_AV_TOTAL
	,sum(MES$Amount) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) MES$Amount
	,sum(Carrier$Amount) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) Carrier$Amount
	,sum(CBH$Amount) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) CBH$Amount
	,sum(National$Amount) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) National$Amount	
	,sum(National_TW$Amount) OVER (PARTITION BY distinct_loc_id, SV_ACCT_ADDR1, SV_ACCT_ADDR2) National_TW$Amount
FROM
	RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc
	) a
	WHERE
		rnk = 1
	ORDER BY 
		root_customer_name, ROOT_ACCOUNT_NUMBER ,ACCT_NUM
--401,958 records

CREATE NONCLUSTERED INDEX ix_SCA_MODULE_STAGE1sv_biller_mrc_loc1 ON RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao(ROOT_ACCOUNT_NUMBER,ACCT_NUM,AANCUT) 
CREATE CLUSTERED INDEX ix_SCA_MODULE_STAGE1sv_biller_mrc_loc2 ON RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao(AAN4,SV_EXCL_IND) 

alter table RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao drop column SVM_BUSN_ID, SVM_HQ_ID,SVAN_BUSN_ID ,SVAN_HQ_ID ,CSG_BUSN_ID ,CSG_HQ_ID 
ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao add SVM_BUSN_ID BIGINT,SVM_HQ_ID BIGINT,SVAN_BUSN_ID BIGINT,SVAN_HQ_ID BIGINT,CSG_BUSN_ID BIGINT,CSG_HQ_ID BIGINT


--drop table #UPDATESVMBUSNID



SELECT 
	distinct c.HQ_ID, b.ath_busn_id, b.ROOT_ACCOUNT_NAME, b.PRODUCT_INSTANCE_ID as PRODUCT_INSTANCE_IDjoin, SV_ACCT_ADDR1
INTO
	#UPDATESVMBUSNID	
FROM
	rptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao a
left join
	BI_MIP.[MIP3].[SV_SOURCE_ADDR] b 
	on a.PRODUCT_INSTANCE_ID = b.PRODUCT_INSTANCE_ID and b.ROOT_ACCOUNT_NAME = a.ROOT_ACCOUNT_NUMBER
left join
	EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE c on c.BUSN_ID = b.ATH_BUSN_ID
--318,822 rows


select * from #UPDATESVMBUSNID where ROOT_ACCOUNT_NAME = 900010165

--update both SV BUSN_ID and HQ ID in same statement
UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVM_BUSN_ID = ath_busn_id, SVM_HQ_ID = HQ_ID 
FROM #UPDATESVMBUSNID  
WHERE PRODUCT_INSTANCE_ID = PRODUCT_INSTANCE_IDjoin AND ROOT_ACCOUNT_NUMBER =  ROOT_ACCOUNT_NAME

---- 295,631 rows affected (BUSN_ID & HQ_ID)


--select top 100000  root_account_number, acct_num,SV_ACCT_ADDR1 ,SVM_BUSN_ID, SVM_HQ_ID,SVAN_BUSN_ID ,SVAN_HQ_ID ,CSG_BUSN_ID ,CSG_HQ_ID from RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao  -- where CSG_BUSN_ID is NOT NULL

--since [SV_SOURCE_ADDR] only has root_account_number and not acct_num, not expecting too many updates here
UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVAN_BUSN_ID = ath_busn_id, SVAN_HQ_ID = HQ_ID
FROM #UPDATESVMBUSNID  
WHERE PRODUCT_INSTANCE_ID = PRODUCT_INSTANCE_IDjoin AND ACCT_NUM =  ROOT_ACCOUNT_NAME

---- 41,236 rows affected (BUSN_ID & HQ_ID)



--Using another table to find SVAN BUSN and HQ_IDs.  
--This data will not be at the site level because we are only joining on ACCT_NUM. 
--Will need to JOIN on a street name as well eventualy

drop table #SVAN_BUSN_HQ_ID;

SELECT a.BUSN_ID, a.CMCST_BILLING_SYSTEM, a.CMCST_ACCOUNT_NUMBER, a.CMCST_ACCOUNT_STATUS, b.ATHENA_ADDRESS, b.ATHENA_BUSINESS_HQ_ID, NAX_ADDRESS_ID, ATHENA_BUSINESS_NAME
INTO #SVAN_BUSN_HQ_ID
FROM EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE_ACCOUNT_DIM a
LEFT JOIN (SELECT
		ATHENA_ADDRESS, ATHENA_BUSINESS_HQ_ID, ATHENA_BUSINESS_ID, ATHENA_BUSINESS_NAME, NAX_ADDRESS_ID
	  FROM
		BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY
	  ) b  on busn_id= ATHENA_BUSINESS_ID
RIGHT JOIN
	 (SELECT 
		DISTINCT ROOT_ACCOUNT_NUMBER, 
		ACCT_NUM
	  FROM 
		RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
	 ) c ON a.CMCST_ACCOUNT_NUMBER = ACCT_NUM
 --and ATHENA_ADDRESS = '1000 ADAMS AVE'
order by
	 busn_id

--395,237 records


UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVAN_BUSN_ID = b.BUSN_ID
FROM #SVAN_BUSN_HQ_ID  b
WHERE SVAN_BUSN_ID is NULL AND (ACCT_NUM = b.CMCST_ACCOUNT_NUMBER)

--281,973 records

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVAN_HQ_ID = ATHENA_BUSINESS_HQ_ID
FROM #SVAN_BUSN_HQ_ID  b
WHERE SVAN_HQ_ID is NULL AND (ACCT_NUM = b.CMCST_ACCOUNT_NUMBER)

--282,357 records

--Using another table to find SVM BUSN and HQ_IDs.  

SELECT a.BUSN_ID, a.CMCST_BILLING_SYSTEM, a.CMCST_ACCOUNT_NUMBER, a.CMCST_ACCOUNT_STATUS, b.ATHENA_ADDRESS, b.ATHENA_BUSINESS_HQ_ID, NAX_ADDRESS_ID, ATHENA_BUSINESS_NAME
INTO #SVM_BUSN_HQ_ID
FROM EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE_ACCOUNT_DIM a
LEFT JOIN (SELECT
		ATHENA_ADDRESS, ATHENA_BUSINESS_HQ_ID, ATHENA_BUSINESS_ID, ATHENA_BUSINESS_NAME, NAX_ADDRESS_ID
	  FROM
		BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY
	  ) b  on busn_id= ATHENA_BUSINESS_ID
RIGHT JOIN
	 (SELECT 
		DISTINCT ROOT_ACCOUNT_NUMBER
	  FROM 
		RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
	 ) c ON a.CMCST_ACCOUNT_NUMBER = ROOT_ACCOUNT_NUMBER
 --and ATHENA_ADDRESS = '1000 ADAMS AVE'
order by
	 busn_id

--119,XXX records

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVM_BUSN_ID = BUSN_ID
FROM #SVM_BUSN_HQ_ID  b
WHERE SVM_BUSN_ID is NULL AND (ROOT_ACCOUNT_NUMBER = b.CMCST_ACCOUNT_NUMBER)

--101,720 records

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 
SET SVAN_HQ_ID = ATHENA_BUSINESS_HQ_ID
FROM #SVM_BUSN_HQ_ID  b
WHERE SVM_HQ_ID is NULL AND (ROOT_ACCOUNT_NUMBER = b.CMCST_ACCOUNT_NUMBER)

--103,179 records

select top 10000 * from RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao 



drop table RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO

SELECT 
LOAD_DT,
1111111111111111 FAMILY_ID,
'SV+CSG' FILE_GROUP,
CSG_BUSN_ID,
CSG_HQ_ID,
SVM_BUSN_ID,
SVM_HQ_ID,
SVAN_BUSN_ID,
SVAN_HQ_ID,
ROOT_ACCOUNT_NUMBER SV_ROOT_ACCOUNT,
ACCT_NUM SV_ACCOUNT,
INVOICE_ACCOUNT_NAME SV_ROOT_ACCOUNT_NAME,
SV_WD_SITE,
SERVICE_A_GEOCODE,
DISTINCT_LOC_ID,
SV_ACCT_ADDR1,
SV_ACCT_ADDR2,
SV_ACCT_CITY,
SV_ACCT_STATE,
SV_ACCT_ZIP,
SV_MRC_TOTAL,
SV_MRC_METROE,
SV_MRCsubset_AV_PRI,
SV_MRCsubset_AV_SIP,
SV_MRCsubset_AV_BVE,
SV_MRC_AV_TOTAL,
MES$Amount,
Carrier$Amount,
CBH$Amount,
National$Amount,
National_TW$Amount,
NAT_IND,GOV_IND,EDU_IND,AGGR_IND,MES_IND,CAR_IND,CBH_IND,HSPY_IND,TWKR_IND,SV_EXCL_IND,
AAN SV_AAN,
AANCUT,
AAN4 CSG4,
ACCOUNT_NUMBER			CSG_ACCOUNT,
DIVISION_NAME			CSG_DIV_BCS,
REGION_NAME				CSG_REGION_BCS,
ACCOUNT_HOLDER_NAME		CSG_BUSN_NAME,
ADDRESS_LINE1_TXT		CSG_ADDR1,
ADDRESS_LINE2_TXT		CSG_ADDR2,
CITY_NAME				CSG_CITY,
STATE_CODE				CSG_STATE,
ZIP_CODE				CSG_ZIP,
PHONE_NUMBER			CSG_BUSN_PHONE, 
HOUSE_KEY				CSG_HOUSEKEY,
BILLING_DWELL_TYPE_CODE CSG_DWELL_CODE,
DWELLING_DESCRIPTION_1	CSG_DWELL_DESCR_BCS1,
DWELLING_DESCRIPTION_2  CSG_DWELL_DESCR_BCS2,
DWELLING_DESCRIPTION_3	CSG_DWELL_DESCR_BCS3,
'                           ' CSG_DWELL_DESCR_WD1,
'                           ' CSG_DWELL_DESCR_WD2,
'                           ' CSG_DWELL_DESCR_WD3,
'?' GOV_IND_CSG,
'?' EDU_IND_CSG,
'?' CSG_EXCL_IND,
BCV_IND				CSG_VOICE_IND,
BCI_IND				CSG_DATA_IND,
VIDEO_IND			CSG_VIDEO_IND,
WIFIPRO_IND			CSG_WIFIPRO_IND,
CONNECTION_PRO_IND	CSG_CONNPRO_IND,
'?' CSG_SECEDGE_IND,
TELEWORKER_IND		CSG_TW_IND,

ISNULL(BCV_MRC_AMT,0.00)		CSG_VOICE_MRC,
ISNULL(BCI_MRC_AMT,0.00)		CSG_DATA_MRC,
ISNULL(VIDEO_MRC_AMT,0.00)		CSG_VIDEO_MRC,
ISNULL(CONNECTION_PRO_MRC,0.00)	CSG_CONNPRO_MRC_BCS,
ISNULL(TOTAL_MRC_AMT,0.00) - (ISNULL(BCV_MRC_AMT,0.00)+ISNULL(BCI_MRC_AMT,0.00)+ISNULL(VIDEO_MRC_AMT,0.00)+ISNULL(CONNECTION_PRO_MRC,0.00)/*+ISNULL(CSG_WIFIPRO_MRC,0)*/)	CSG_OTHER_MRC_BCS,
ISNULL(TOTAL_MRC_AMT,0.00)		CSG_TOTAL_MRC_BCS,
0.00							CSG_CONNPRO_MRC_WD,
0.00							CSG_WIFIPRO_MRC_WD,
0.00							CSG_SECEDGE_MRC_WD,
0.00							CSG_OTHER_MRC_BCS_WD,
0.00							CSG_TOTAL_MRC_BCS_WD,
ORIGINAL_CONNECT_DATE CSG_ORIG_CONN_DT,
BCV_CONNECT_DATE	  CSG_VOICE_CONN_DT,
BCI_CONNECT_DATE	  CSG_DATA_CONN_DT,
TENURE_MONTHS CSG_TENURE_MNTHS
--,null,null,null,null,null,null,null
INTO RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
FROM RptCB.Rpt.SCA_MODULE_STAGE1sv_biller_mrc_loc_dyao
LEFT OUTER JOIN [ExternalUser].[NDW].[BC_SUBS_JV]
ON AANCUT = ACCOUNT_NUMBER AND (DISCONNECTED_ACCOUNT_IND = 0 AND BUSINESS_INTERNET_COURTESY_IND = 0 AND BUSINESS_VOICE_COURTESY_IND = 0) 
AND (CONCAT(BCV_IND,BCI_IND,VIDEO_IND) LIKE '%1%'
	OR (ISNULL(BCV_MRC_AMT,0.00)+ISNULL(BCI_MRC_AMT,0.00)+ISNULL(VIDEO_MRC_AMT,0.00)) >0  
	)
and isnull(ROOT_ACCOUNT_NUMBER,'') <> ''
where aancut is null or CONVERT(DATE,RECORD_END_TS) = '9999-12-31'

--351,487 rows

DROP INDEX ix_SCA_MODULE_STAGE1Xa on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
create nonclustered index ix_SCA_MODULE_STAGE1Xa on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO (SV_ROOT_ACCOUNT,SV_ACCOUNT,CSG_ACCOUNT)

DROP INDEX ix_SCA_MODULE_STAGE1Xb on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
create nonclustered index ix_SCA_MODULE_STAGE1Xb on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO (CSG4,CSG_ACCOUNT,CSG_HOUSEKEY,CSG_DWELL_CODE)

DROP INDEX ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
create nonclustered index ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO (FILE_GROUP,CSG_BUSN_ID,CSG_HQ_ID,SVM_BUSN_ID,SVM_HQ_ID,SVAN_BUSN_ID,SVAN_HQ_ID) --FAMILY_ID


--select  * from RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO tablesample(1 percent)  -- where CSG_BUSN_ID is NOT NULL
--drop table #CSG_BUSN_HQ_ID

--Now to find BUSN and HQ IDs using CSG AAN number
SELECT a.BUSN_ID, a.CMCST_BILLING_SYSTEM, a.CMCST_ACCOUNT_NUMBER, a.CMCST_ACCOUNT_STATUS, b.ATHENA_ADDRESS, b.ATHENA_BUSINESS_HQ_ID, NAX_ADDRESS_ID, ATHENA_BUSINESS_NAME
INTO #CSG_BUSN_HQ_ID
FROM EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE_ACCOUNT_DIM a
LEFT JOIN (SELECT
		ATHENA_ADDRESS, ATHENA_BUSINESS_HQ_ID, ATHENA_BUSINESS_ID, ATHENA_BUSINESS_NAME, NAX_ADDRESS_ID
	  FROM
		BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY
	  ) b  on busn_id= ATHENA_BUSINESS_ID
RIGHT JOIN
	 (SELECT 
		DISTINCT AANCUT
	  FROM 
		RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  
	 ) c ON a.CMCST_ACCOUNT_NUMBER = c.AANCUT
 --and ATHENA_ADDRESS = '1000 ADAMS AVE'
order by
	 busn_id

--277,496 records


UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
SET CSG_BUSN_ID = BUSN_ID, CSG_HQ_ID = ATHENA_BUSINESS_HQ_ID
FROM #CSG_BUSN_HQ_ID  b
WHERE FILE_GROUP = 'SV+CSG' AND AANCUT = b.CMCST_ACCOUNT_NUMBER
---- 274,636 ROWS IN 12MIN 23SEC




INSERT INTO RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
SELECT 
GETDATE() LOAD_DT,
1111111111111111 FAMILY_ID,
'CSG' FILE_GROUP,
NULL CSG_BUSN_ID,
NULL CSG_HQ_ID,
NULL SVM_BUSN_ID,
NULL SVM_HQ_ID,
NULL SVAN_BUSN_ID,
NULL SVAN_HQ_ID,
NULL SV_ROOT_ACCOUNT,
NULL SV_ACCOUNT,
NULL SV_ROOT_ACCOUNT_NAME,
NULL SV_WD_SITE,
NULL SERVICE_A_GEOCODE,
CAST(ACCOUNT_NUMBER AS VARCHAR(16)) DISTINCT_LOC_ID,
NULL SV_ACCT_ADDR1,
NULL SV_ACCT_ADDR2,
NULL SV_ACCT_CITY,
NULL SV_ACCT_STATE,
NULL SV_ACCT_ZIP,
0 SV_MRC_TOTAL,
0 SV_MRC_METROE,
0 SV_MRCsubset_AV_PRI,
0 SV_MRCsubset_AV_SIP,
0 SV_MRCsubset_AV_BVE,
0 SV_MRC_AV_TOTAL,
0 MES$Amount,
0 Carrier$Amount,
0 CBH$Amount,
0 National$Amount,
0 National_TW$Amount,
NULL NAT_IND,NULL GOV_IND,NULL EDU_IND,NULL AGGR_IND,NULL MES_IND,NULL CAR_IND,NULL CBH_IND,NULL HSPY_IND,NULL TWKR_IND,NULL SV_EXCL_IND,
NULL SV_AAN,
NULL AANCUT,
LEFT(ACCOUNT_NUMBER,4)  CSG4,
ACCOUNT_NUMBER			CSG_ACCOUNT,
DIVISION_NAME			CSG_DIV_BCS,
REGION_NAME				CSG_REGION_BCS,
ACCOUNT_HOLDER_NAME		CSG_BUSN_NAME,
ADDRESS_LINE1_TXT		CSG_ADDR1,
ADDRESS_LINE2_TXT		CSG_ADDR2,
CITY_NAME				CSG_CITY,
STATE_CODE				CSG_STATE,
ZIP_CODE				CSG_ZIP,
PHONE_NUMBER			CSG_BUSN_PHONE, 
HOUSE_KEY				CSG_HOUSEKEY,
BILLING_DWELL_TYPE_CODE CSG_DWELL_CODE,
DWELLING_DESCRIPTION_1	CSG_DWELL_DESCR_BCS1,
DWELLING_DESCRIPTION_2  CSG_DWELL_DESCR_BCS2,
DWELLING_DESCRIPTION_3	CSG_DWELL_DESCR_BCS3,
'                           ' CSG_DWELL_DESCR_WD1,
'                           ' CSG_DWELL_DESCR_WD2,
'                           ' CSG_DWELL_DESCR_WD3,
'?' GOV_IND_CSG,
'?' EDU_IND_CSG,
'?' CSG_EXCL_IND,
BCV_IND				CSG_VOICE_IND,
BCI_IND				CSG_DATA_IND,
VIDEO_IND			CSG_VIDEO_IND,
WIFIPRO_IND			CSG_WIFIPRO_IND,
CONNECTION_PRO_IND	CSG_CONNPRO_IND,
'?' CSG_SECEDGE_IND,
TELEWORKER_IND		CSG_TW_IND,

ISNULL(BCV_MRC_AMT,0.00)		CSG_VOICE_MRC,
ISNULL(BCI_MRC_AMT,0.00)		CSG_DATA_MRC,
ISNULL(VIDEO_MRC_AMT,0.00)		CSG_VIDEO_MRC,
ISNULL(CONNECTION_PRO_MRC,0.00)	CSG_CONNPRO_MRC_BCS,
ISNULL(TOTAL_MRC_AMT,0.00) - (ISNULL(BCV_MRC_AMT,0.00)+ISNULL(BCI_MRC_AMT,0.00)+ISNULL(VIDEO_MRC_AMT,0.00)+ISNULL(CONNECTION_PRO_MRC,0.00)/*+ISNULL(CSG_WIFIPRO_MRC,0)*/)	CSG_OTHER_MRC_BCS,
ISNULL(TOTAL_MRC_AMT,0.00)		CSG_TOTAL_MRC_BCS,
0.00							CSG_CONNPRO_MRC_WD,
0.00							CSG_WIFIPRO_MRC_WD,
0.00							CSG_SECEDGE_MRC_WD,
0.00							CSG_OTHER_MRC_BCS_WD,
0.00							CSG_TOTAL_MRC_BCS_WD,
ORIGINAL_CONNECT_DATE CSG_ORIG_CONN_DT,
BCV_CONNECT_DATE	  CSG_VOICE_CONN_DT,
BCI_CONNECT_DATE	  CSG_DATA_CONN_DT,
TENURE_MONTHS CSG_TENURE_MNTHS --- SELECT COUNT(*) CNT
FROM [ExternalUser].[NDW].[BC_SUBS_JV] AS B
WHERE DIVISION_NAME = 'WEST DIVISION' AND (DISCONNECTED_ACCOUNT_IND = 0 AND BUSINESS_INTERNET_COURTESY_IND = 0 AND BUSINESS_VOICE_COURTESY_IND = 0) AND CONVERT(DATE,RECORD_END_TS) = '9999-12-31'
AND (ISNULL(BCV_IND,0)+ISNULL(BCI_IND,0)+ISNULL(VIDEO_IND,0)+ISNULL(BCV_MRC_AMT,0.00)+ISNULL(BCI_MRC_AMT,0.00)+ISNULL(VIDEO_MRC_AMT,0.00)) >0  
AND ACCOUNT_NUMBER NOT IN ( SELECT DISTINCT CSG_ACCOUNT FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  WITH (NOLOCK) WHERE CSG4  in ('8155','8777','8497','8498','8772','8778','8495','8512')  AND CSG_ACCOUNT IS NOT NULL )--- 117343
---- 618,779 ROWS IN 1MIN 18SEC

DROP INDEX ix_SCA_MODULE_STAGE1Xa on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO; 
create nonclustered index ix_SCA_MODULE_STAGE1Xa on RptCB.Rpt.SCA_MODULE_STAGE1X (FILE_GROUP,SV_ROOT_ACCOUNT,SV_ACCOUNT,CSG_ACCOUNT);
DROP INDEX ix_SCA_MODULE_STAGE1Xb on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO;
create nonclustered index ix_SCA_MODULE_STAGE1Xb on RptCB.Rpt.SCA_MODULE_STAGE1X (FILE_GROUP,CSG4,CSG_ACCOUNT,CSG_HOUSEKEY,CSG_DWELL_CODE);
DROP INDEX ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ;
create nonclustered index ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X (CSG_BUSN_ID,CSG_HQ_ID,SVM_BUSN_ID,SVM_HQ_ID,SVAN_BUSN_ID,SVAN_HQ_ID);--FAMILY_ID,


SELECT a.BUSN_ID, a.CMCST_BILLING_SYSTEM, a.CMCST_ACCOUNT_NUMBER, a.CMCST_ACCOUNT_STATUS, b.ATHENA_ADDRESS, b.ATHENA_BUSINESS_HQ_ID, NAX_ADDRESS_ID, ATHENA_BUSINESS_NAME
INTO #CSG_ONLY_BUSN_HQ_ID
FROM EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE_ACCOUNT_DIM a
LEFT JOIN (SELECT
		ATHENA_ADDRESS, ATHENA_BUSINESS_HQ_ID, ATHENA_BUSINESS_ID, ATHENA_BUSINESS_NAME, NAX_ADDRESS_ID
	  FROM
		BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY
	  ) b  on busn_id= ATHENA_BUSINESS_ID
RIGHT JOIN
	 (SELECT 
		DISTINCT CSG_ACCOUNT
	  FROM 
		RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  
	  WHERE
		FILE_GROUP ='CSG'
	 ) c ON a.CMCST_ACCOUNT_NUMBER = c.CSG_ACCOUNT
 --and ATHENA_ADDRESS = '1000 ADAMS AVE'
order by
	 busn_id

--618,822 rows

drop table #CSG_ONLY_BUSN_HQ_ID
/*
SELECT a.*
INTO #CSG_ONLY_BUSN_HQ_ID
FROM BI_MIP.[MIP3].[ATHENA_CUSTOMER_ACCOUNT] a
RIGHT JOIN
	 (SELECT 
		DISTINCT CSG_ACCOUNT
	  FROM 
		RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  
	  WHERE
		FILE_GROUP ='CSG'
	 ) c ON a.CMCST_ACCOUNT_NUMBER = c.CSG_ACCOUNT
*/

--Get BUSN and HQ IDs for CSG only accounts
UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
SET CSG_BUSN_ID = BUSN_ID, CSG_HQ_ID = ATHENA_BUSINESS_HQ_ID
FROM #CSG_ONLY_BUSN_HQ_ID  b
WHERE FILE_GROUP = 'CSG' AND CSG_ACCOUNT = b.CMCST_ACCOUNT_NUMBER
---- 595,349 ROWS IN 18SEC
---- Still have roughly 23K rows with no BUSN or HQ_ID



UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
SET CSG_BUSN_ID = athena_business_id
FROM BI_MIP.MIP3.ATHENA_BUSINESS_XREF
WHERE CSG_BUSN_ID is NULL and FILE_GROUP = 'CSG' AND  CSG_ACCOUNT = SOURCE_ID AND CSG_ACCOUNT IS NOT NULL AND source_nm =  'CSG ACCOUNTS' 
--533 rows 

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
SET CSG_HQ_ID = CASE WHEN FILE_GROUP = 'CSG' AND HQ_ID IS NOT NULL THEN HQ_ID
WHEN FILE_GROUP = 'CSG' AND HQ_ID IS NULL THEN CSG_BUSN_ID 
					 WHEN FILE_GROUP <> 'CSG' AND ( HQ_ID = ISNULL(SVAN_HQ_ID,'')  
													OR HQ_ID = ISNULL(SVM_HQ_ID,'') ) THEN NULL 
					 ELSE HQ_ID END
FROM EXTERNALUSER.MIP.MIP3_BUSINESS_PROFILE ----FILE_GROUP = 'CSG' AND  
WHERE FILE_GROUP = 'CSG' AND CSG_HQ_ID is NULL AND CSG_BUSN_ID = BUSN_ID AND CSG_BUSN_ID IS NOT NULL 
--531 rows 


DROP INDEX ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X 
create nonclustered index ix_SCA_MODULE_STAGE1Xc on RptCB.Rpt.SCA_MODULE_STAGE1X (CSG_BUSN_ID,CSG_HQ_ID,SVM_BUSN_ID,SVM_HQ_ID,SVAN_BUSN_ID,SVAN_HQ_ID) --FAMILY_ID,

Select 
SubAccount
,Sum(ConnPro_MRC) as ConnPro_MRC
,Sum(WifiPro_MRC) as WifiPro_MRC
,Sum(SecurityEdge_MRC) as SecurityEdge_MRC
INTO #TMP_MRC_update
From
( Select SUB_ACCT_NO_OCI as SubAccount
		, Case When SERV_CDE_OCI in ('HSCHV','HSCHW') then COALESCE((itv.aft_qty_itv * itv.monthly_value_amt_itv),(oci.aft_qty_oci * oci.charge_amt_oci))   Else 0 End as ConnPro_MRC
		, Case When SERV_CDE_OCI in ('HSCGA','HSCGB','HSCGC','HSCGD','HSCGV','HSCGW') then COALESCE((itv.aft_qty_itv * itv.monthly_value_amt_itv),(oci.aft_qty_oci * oci.charge_amt_oci))  Else 0 End as WifiPro_MRC
		, Case When SERV_CDE_OCI in ('HSCKJ') then COALESCE((itv.aft_qty_itv * itv.monthly_value_amt_itv),(oci.aft_qty_oci * oci.charge_amt_oci))  Else 0 End as SecurityEdge_MRC
			--   SELECT SUM(oci.aft_qty_oci * oci.charge_amt_oci) MRC  ---- 512.55
		From RptCB.Rpt.SCA_MODULE_STAGE1X  
		join ExternalUser.[Vantage].[OCI_CUR_ITEM] as OCI
			ON CSG_ACCOUNT =  oci.SUB_ACCT_NO_OCI 
	   left join [ExternalUser].[Vantage].[ITV_ITEM_VALUE] as ITV
			on ITV.SUB_ACCT_NO_ITV = oci.SUB_ACCT_NO_OCI 
			and cast(getdate() as date) between itv.value_start_dte_itv and itv.value_end_dte_itv	
			and 	oci.SERV_CDE_OCI = itv.SERV_CDE_ITV	
			and	oci.serv_id_oci = CAST(itv.serv_id_itv AS INT)
		WHERE oci.SERV_CDE_OCI in ('HSCKJ','HSCHV','HSCHW','HSCGA','HSCGB','HSCGC','HSCGD','HSCGV','HSCGW') 
)as d
group by d.SubAccount 


ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ALTER COLUMN CSG_CONNPRO_MRC_WD NUMERIC(15,2); 
ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ALTER COLUMN CSG_WIFIPRO_MRC_WD NUMERIC(15,2);  
ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ALTER COLUMN CSG_SECEDGE_MRC_WD NUMERIC(15,2);  

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X 
SET CSG_CONNPRO_MRC_WD= ISNULL(ConnPro_MRC,0.00),
	CSG_WIFIPRO_MRC_WD = ISNULL(WifiPro_MRC,0.00),
	CSG_SECEDGE_MRC_WD = ISNULL(SecurityEdge_MRC,0.00)
FROM #TMP_MRC_update WHERE SubAccount = CSG_ACCOUNT AND CSG4 in ('8155','8777','8497','8498','8772','8778','8495','8512') 

--73,774 rows

ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ALTER COLUMN [CSG_OTHER_MRC_BCS] NUMERIC(15,2); 
ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO ALTER COLUMN [CSG_TOTAL_MRC_BCS_WD] NUMERIC(16,3);  

UPDATE A
SET [CSG_OTHER_MRC_BCS] = [CSG_TOTAL_MRC_BCS] - ([CSG_VOICE_MRC]+[CSG_DATA_MRC]+[CSG_VIDEO_MRC]+[CSG_CONNPRO_MRC_BCS]+[CSG_OTHER_MRC_BCS])
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A

UPDATE A
SET [CSG_TOTAL_MRC_BCS_WD] = (CSG_WIFIPRO_MRC_WD+CSG_CONNPRO_MRC_WD+CSG_SECEDGE_MRC_WD+[CSG_TOTAL_MRC_BCS])
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A

UPDATE A
SET FAMILY_ID = 0
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A

UPDATE A
SET GOV_IND_CSG = '',
EDU_IND_CSG = '',
CSG_EXCL_IND = '',
CSG_SECEDGE_IND = '?'
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A
WHERE GOV_IND_CSG = '?' AND EDU_IND_CSG = '?' AND EDU_IND_CSG = '?' AND CSG_SECEDGE_IND = '?'

UPDATE A
SET CSG_SECEDGE_IND = '1'
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A
WHERE CSG_SECEDGE_MRC_WD > 0

UPDATE A
SET CSG_WIFIPRO_IND = '1'
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A
WHERE CSG_WIFIPRO_MRC_WD > 0

UPDATE A
SET CSG_CONNPRO_IND = '1'
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as A
WHERE CSG_CONNPRO_MRC_WD > 0


--ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  ADD SITE_TOTAL_MRC NUMERIC(15,2)

UPDATE A 
SET SITE_TOTAL_MRC = (ISNULL(SV_MRC_TOTAL,0))+(ISNULL(CSG_TOTAL_MRC_BCS_WD,0))
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  AS A


ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  ADD CSG_HBB_IND VARCHAR(1) ;

WITH CSGEXCL AS (
 select distinct 
 CSG_DWELL_CODE CSG_DWELL_CODEjoin,	CSG_DWELL_DESCR_WD1 CDW1,	CSG_DWELL_DESCR_WD2 CDW2,	CSG_DWELL_DESCR_WD3 CDW3,
 CASE WHEN CSG_DWELL_DESCR_WD3 = 'GOVERNMENT' THEN 'Y' WHEN TEST_FOR_IND LIKE '%GOVERNMENT%' THEN 'Y' 
	  WHEN TEST_FOR_IND LIKE '%GVMT%' THEN 'Y' ELSE '' END CSG_GOV_INDnew,

 CASE WHEN TEST_FOR_IND LIKE '%COLLEGE%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%SCHOOL%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%UNINVERSITY%' THEN 'Y'ELSE '' END  CSG_EDU_INDnew ,

 CASE WHEN CSG_DWELL_DESCR_BCS2 = 'RESIDENTIAL' THEN 'Y' WHEN TEST_FOR_IND LIKE '%RESI_%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%RESIDENTIAL%' THEN 'Y' ELSE '' END CSG_HBB_INDnew,

  CASE WHEN CSG_DWELL_DESCR_WD2 = 'COMCAST_OFFICE_TEST' THEN 'Y' WHEN CSG_DWELL_DESCR_WD3 = 'GOVERNMENT' THEN 'Y' WHEN TEST_FOR_IND LIKE '%GOVERNMENT%' THEN 'Y' 
	  WHEN TEST_FOR_IND LIKE '%GVMT%' THEN 'Y'
  WHEN TEST_FOR_IND LIKE '%COLLEGE%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%SCHOOL%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%UNINVERSITY%' THEN 'Y'
  WHEN CSG_DWELL_DESCR_BCS2 = 'RESIDENTIAL' THEN 'Y' WHEN TEST_FOR_IND LIKE '%RESI_%' THEN 'Y' WHEN TEST_FOR_IND LIKE '%RESIDENTIAL%' THEN 'Y' ELSE '' END  CSG_EXCL_INDnew
from(
	 select distinct
	x.CSG_DWELL_CODE,x.CSG_DWELL_DESCR_BCS1,x.CSG_DWELL_DESCR_BCS2,x.CSG_DWELL_DESCR_BCS3,
	d.UnitsView CSG_DWELL_DESCR_WD1,
	CASE WHEN d.DwellingCatName IN ('Not Used','Unknown') THEN '' ELSE d.DwellingCatName  END CSG_DWELL_DESCR_WD2,
	CASE WHEN d.DwellingSubCatName IN ('Not Used','Unknown') THEN '' ELSE d.DwellingSubCatName  END CSG_DWELL_DESCR_WD3,
	 CONCAT(CSG_DWELL_CODE	,CSG_DWELL_DESCR_BCS1,	CSG_DWELL_DESCR_BCS2,	CSG_DWELL_DESCR_BCS3, d.UnitsView ,CASE WHEN d.DwellingCatName IN ('Not Used','Unknown') THEN '' ELSE d.DwellingCatName  END ,
	CASE WHEN d.DwellingSubCatName IN ('Not Used','Unknown') THEN '' ELSE d.DwellingSubCatName  END ) TEST_FOR_IND
	  ---- select distinct csg4
	FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as x
	join wisdm.dim.dwelling as d
	on CSG_DWELL_CODE = d.DwellingCode 
	and csg4 = d.[sys] and 
	case when csg4 in ('8495','8772') then substring(csg_account,5,4) else 0 end = d.prin 
	WHERE isnull(CSG4,'XCSG') <> 'XCSG' and isnumeric(csg_account) = 1
) AS EX
)
UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
SET CSG_DWELL_DESCR_WD1 = CDW1,
	CSG_DWELL_DESCR_WD2	= CDW2,
	CSG_DWELL_DESCR_WD3	= CDW3,
	GOV_IND_CSG	= CSG_GOV_INDnew,
	EDU_IND_CSG	= CSG_EDU_INDnew,
	CSG_EXCL_IND = CSG_EXCL_INDnew,
    CSG_HBB_IND = CSG_HBB_INDnew                     	                           	                           			
FROM CSGEXCL WHERE CSG_DWELL_CODE = CSG_DWELL_CODEjoin
and  isnull(CSG4,'XCSG') <> 'XCSG' and isnumeric(CSG_ACCOUNT) = 1


SELECT DISTINCT MOD_BUSN_ID,COUNT(DISTINCT DISTINCT_LOC_ID) MOD_BUSN_ID_CNT
INTO #FULL_BUSN_ID_LIST FROM (
 SELECT DISTINCT 
SVM_BUSN_ID MOD_BUSN_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
UNION ALL
SELECT DISTINCT 
SVM_HQ_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
UNION ALL
SELECT DISTINCT 
SVAN_BUSN_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
UNION ALL
SELECT DISTINCT 
SVAN_HQ_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
UNION ALL
SELECT DISTINCT 
CSG_BUSN_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
UNION ALL
SELECT DISTINCT
CSG_HQ_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
) AS B
group by MOD_BUSN_ID

select top 1000 * from #FULL_BUSN_ID_LIST


--DROP TABLE  #temp_ATHENA_INFO_LOAD
SELECT 
MOD_BUSN_ID MOD_BUSN_IDnew,MOD_BUSN_ID_CNT MOD_BUSN_ID_CNTnew,SM.ATHENA_BUSINESS_LEGAL_NAME ATHENA_LEGAL_NAMEnew,
	   B.MIP_SUITE_SELLABILITY_COLOR_COAX COAX_SELLCOLORnew,B.MIP_SUITE_SELLABILITY_COLOR_FIBER FIBER_SELLCOLORnew,
	   CASE WHEN A.ATH_SEGMENT = 'SMB' THEN 'SMALL-MEDIUM'
			WHEN A.ATH_SEGMENT = 'MID-MARKET' THEN 'MID-MARKET'
			WHEN A.ATH_SEGMENT = 'ENTERPRISE' AND A.ATH_SUBSEGMENT = 'NATIONAL' THEN 'NATIONAL'
			WHEN A.ATH_SEGMENT = 'ENTERPRISE' AND A.ATH_SUBSEGMENT = 'STRATEGIC' THEN 'STRATEGIC'
			WHEN A.ATH_SEGMENT = 'MID-MARKET' AND A.ATH_SUBSEGMENT = 'MAJOR' THEN 'MAJOR'
			WHEN A.ATH_SEGMENT = 'GOVERNMENT' OR (A.ATH_SEGMENT = 'MID-MARKET' AND A.ATH_SUBSEGMENT = 'EDUCATION') THEN 'GOVED'
			WHEN A.ATH_SEGMENT = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL') THEN 'MID-MARKET'
			ELSE NULL END AS ATHENA_SEGMENTnew,
	   ATH_MONTHLY_TELCO_SPEND AS ATHENA_SITE_TELCO_MOMnew,
	    CASE WHEN A.ATH_SUBSEGMENT = 'MAJOR' THEN 'MAJOR'
	        WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND IS NULL OR  SM.ATHENA_SITE_EST_TOTAL_SPEND <= 100 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) )   THEN '100 OR LESS'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 100 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 200 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '100 TO 200'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 200 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 250 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '200 TO 250'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 250 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 300 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '250 TO 300'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 300 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 400 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '300 TO 400'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 400 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 500 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '400 TO 500'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 500 AND   SM.ATHENA_SITE_EST_TOTAL_SPEND <= 750 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '500 TO 750'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 750 AND  SM.ATHENA_SITE_EST_TOTAL_SPEND <= 1000 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '750 TO 1000'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 1000 AND SM.ATHENA_SITE_EST_TOTAL_SPEND <= 2000 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '1000 TO 2000'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 2000 AND SM.ATHENA_SITE_EST_TOTAL_SPEND <= 3000 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '2000 TO 3000'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 3000 AND SM.ATHENA_SITE_EST_TOTAL_SPEND <= 4000 AND (A.ATH_SEGMENT = 'SMB' OR (A.ATH_SUBSEGMENT  = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '3000 TO 4000'
			WHEN SM.ATHENA_SITE_EST_TOTAL_SPEND > 4000 AND (A.ATH_SUBSEGMENT = 'SMB' OR (A.ATH_SEGMENT = 'MID-MARKET' AND A.ATH_SUBSEGMENT IN ('HOSPITALITY','GENERAL')) ) THEN '4001+'
			WHEN A.ATH_SEGMENT = 'GOVERNMENT' OR (A.ATH_SEGMENT = 'MID-MARKET' AND A.ATH_SUBSEGMENT = 'EDUCATION') THEN 'GOVED'
			WHEN A.ATH_SEGMENT = 'ENTERPRISE' AND A.ATH_SUBSEGMENT = 'NATIONAL' THEN 'NATIONAL'
			WHEN A.ATH_SEGMENT = 'ENTERPRISE' AND A.ATH_SUBSEGMENT = 'STRATEGIC' THEN 'STRATEGIC'
			ELSE NULL END AS ATHENA_SITE_TELCO_BUCKETnew,
			SM.ATHENA_SITE_EST_TOTAL_SPEND,
	   A.ATH_EMPLOYEE_COUNT AS ATHENA_EMP_COUNTnew
	 into #temp_ATHENA_INFO_LOAD ---- SELECT COUNT(*) 
FROM  #FULL_BUSN_ID_LIST T
LEFT JOIN BI_MIP.MIP3.BUSINESS_PROFILE a
on A.ATH_BUSN_ID = MOD_BUSN_ID
LEFT JOIN BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY SM
on SM.ATHENA_BUSINESS_ID = MOD_BUSN_ID
LEFT JOIN BI_MIP.MIP3.ADDRESS_PROFILE B ON A.NAX_ADDRESS_ID = B.NAX_ADDRESS_ID -- 1014808 IN 15MIN 42SEC

CREATE INDEX ix_temp_ATHENA_INFO_LOAD ON #temp_ATHENA_INFO_LOAD (MOD_BUSN_IDnew) 

ALTER TABLE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
ADD 
 ATHENA_LEGAL_NAME1		 varchar(255),
	COAX_SELLCOLOR1			 varchar(25),
	FIBER_SELLCOLOR1			 varchar(25),
	ATHENA_SEGMENT1			 varchar(255),
	ATHENA_SITE_TELCO_MOM1	 numeric(25,2),
	ATHENA_SITE_TELCO_BUCKET1 varchar(255),
	ATHENA_EMP_COUNT1		 int,
	ATHENA_BUSN_ID_USED1		 varchar(15)

update RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
set ATHENA_LEGAL_NAME1		= ATHENA_LEGAL_NAMEnew,
	COAX_SELLCOLOR1			= COAX_SELLCOLORnew,
	FIBER_SELLCOLOR1			= FIBER_SELLCOLORnew,
	ATHENA_SEGMENT1			= ATHENA_SEGMENTnew,
	ATHENA_SITE_TELCO_MOM1	= ATHENA_SITE_TELCO_MOMnew,
	ATHENA_SITE_TELCO_BUCKET1 = ATHENA_SITE_TELCO_BUCKETnew,
	ATHENA_EMP_COUNT1		= ATHENA_EMP_COUNTnew,
	ATHENA_BUSN_ID_USED1		= 'SVM_BUSN_ID'
from #temp_ATHENA_INFO_LOAD
where MOD_BUSN_IDnew = SVM_BUSN_ID
AND SVM_BUSN_ID IS NOT NULL  ---- 290252

update RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
set ATHENA_LEGAL_NAME1		= ATHENA_LEGAL_NAMEnew,
	COAX_SELLCOLOR1			= COAX_SELLCOLORnew,
	FIBER_SELLCOLOR1			= FIBER_SELLCOLORnew,
	ATHENA_SEGMENT1			= ATHENA_SEGMENTnew,
	ATHENA_SITE_TELCO_MOM1	= ATHENA_SITE_TELCO_MOMnew,
	ATHENA_SITE_TELCO_BUCKET1 = ATHENA_SITE_TELCO_BUCKETnew,
	ATHENA_EMP_COUNT1		= ATHENA_EMP_COUNTnew,
	ATHENA_BUSN_ID_USED1		= 'SVAN_BUSN_ID'
from #temp_ATHENA_INFO_LOAD
where MOD_BUSN_IDnew = SVAN_BUSN_ID
AND SVAN_BUSN_ID IS NOT NULL AND ATHENA_BUSN_ID_USED1 IS NULL --- 29

update RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
set ATHENA_LEGAL_NAME1		= ATHENA_LEGAL_NAMEnew,
	COAX_SELLCOLOR1			= COAX_SELLCOLORnew,
	FIBER_SELLCOLOR1			= FIBER_SELLCOLORnew,
	ATHENA_SEGMENT1			= ATHENA_SEGMENTnew,
	ATHENA_SITE_TELCO_MOM1	= ATHENA_SITE_TELCO_MOMnew,
	ATHENA_SITE_TELCO_BUCKET1 = ATHENA_SITE_TELCO_BUCKETnew,
	ATHENA_EMP_COUNT1		= ATHENA_EMP_COUNTnew,
	ATHENA_BUSN_ID_USED1		= 'CSG_BUSN_ID'
from #temp_ATHENA_INFO_LOAD
where MOD_BUSN_IDnew = CSG_BUSN_ID
AND CSG_BUSN_ID IS NOT NULL AND ATHENA_BUSN_ID_USED1 IS NULL --- 595218

----------------------------------------------------------------------------------------------------------------BRING IN FAMILY ID HIERARCHY
update RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
set FAMILY_ID = _FinalFamilyID_
from RPTCB.RPT.FAMILY_ID_YAO AS F 
where  [DISTINCT_LOC_ID] = F._DISTINCT_LOC_ID_ and FAMILY_ID = 0


;WITH FIELD_GROUP_ALTERED_BY_FAMILY AS(
SELECT DISTINCT FAMILY_ID FAMILY_IDjoin FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  WHERE FILE_GROUP = 'SV+CSG' )
update RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO 
set FILE_GROUP = 'CSG^SV'
from FIELD_GROUP_ALTERED_BY_FAMILY
WHERE FAMILY_ID = FAMILY_IDjoin AND FILE_GROUP = 'CSG' and FILE_GROUP <> 'SV+CSG'  AND SV_ROOT_ACCOUNT IS NULL  AND SV_ACCOUNT IS NULL --- 12378

ALTER TABLE  RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO  ADD FAMILY_ID_REGION VARCHAR(50);
SELECT family_id,DISTINCT_LOC_ID,CSG_BUSN_ID	,CSG_HQ_ID,	SVM_BUSN_ID,	SVM_HQ_ID,	SVAN_BUSN_ID,	SVAN_HQ_ID INTO #CKFAM_REGION FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO WHERE FAMILY_ID_REGION IS  NULL


SELECT  FAMILY_ID fm_id ,MOD_HQ_ID,COUNT(DISTINCT DISTINCT_LOC_ID) MOD_BUSN_ID_CNT
INTO #FULL_FAMILY_HQ_ID_LIST2 
FROM (
SELECT DISTINCT 
FAMILY_ID, SVM_HQ_ID MOD_HQ_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO WHERE SVM_HQ_ID IS NOT NULL
--and FAMILY_ID in (select family_id from #CKFAM_REGION) --and family_id_region is not null
UNION ALL
SELECT DISTINCT 
FAMILY_ID,SVAN_HQ_ID, DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO WHERE SVAN_HQ_ID IS NOT NULL
---and FAMILY_ID in (select family_id from #CKFAM_REGION) --and family_id_region is not null
UNION ALL
SELECT DISTINCT
FAMILY_ID,COALESCE(CSG_HQ_ID,CSG_BUSN_ID,CSG_ACCOUNT) SD , DISTINCT_LOC_ID
FROM RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO WHERE CSG_ACCOUNT IS NOT NULL
---and FAMILY_ID in (select family_id from #CKFAM_REGION) --and family_id_region is not null
) AS B
group by FAMILY_ID,MOD_HQ_ID;


with MAXHQIDFORFAMILY as (
select distinct n.*,isnull(CMCST_REGION,'UNKNOWN') CMCST_REGION from(
select  fm_id,FM_HQ_ID 
from (
	select  fm_id ,MOD_HQ_ID,MOD_BUSN_ID_CNT,
	row_number() over (partition by fm_id order by mod_busn_id_cnt desc)  highestIsOne,
	case when row_number() over (partition by fm_id order by mod_busn_id_cnt desc)  = 1 then MOD_HQ_ID else '' end FM_HQ_ID
	from #FULL_FAMILY_HQ_ID_LIST2
	) as x
where FM_HQ_ID <> ''
) as n
JOIN BI_MIP.MIP3.ATHENA_BUSINESS_SUMMARY SM
on SM.ATHENA_BUSINESS_ID = FM_HQ_ID
)


UPDATE  RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
SET FAMILY_ID_REGION = REPLACE(CMCST_REGION,' REGION','')
FROM MAXHQIDFORFAMILY
WHERE FAMILY_ID = fm_id ---- 802960 ---992830
--(872211 rows affected)

;WITH CSG_FAMILY_ID_REGIONFIX AS (
select distinct FM_ID,REPLACE(FM_REGION_IDnew,' REGION','') FM_REGION_IDnew 
from(
	select  FM_ID,
	case when row_number() over (partition by fm_id order by LOCCNT desc)  = 1 then CSG_REGION_BCS else '' end FM_REGION_IDnew
	from (
			SELECT FAMILY_ID FM_ID,CSG_REGION_BCS,COUNT(DISTINCT_LOC_ID) LOCCNT
			FROM  RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO as a
			WHERE FAMILY_ID_REGION is null and FILE_GROUP = 'CSG'
			GROUP BY FAMILY_ID,CSG_REGION_BCS
				) as x
	) AS F
	where FM_REGION_IDnew <> ''
)
--------------------------------------------------------------------------------------------------------------------------UPDATE MISSED 'CSG' WD SITES WITH UNKNOWN FAMILY HQ REGION TO HQ_ID WITH MOST SITES
UPDATE  RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
SET FAMILY_ID_REGION = FM_REGION_IDnew
FROM  CSG_FAMILY_ID_REGIONFIX
WHERE FAMILY_ID = FM_ID
--(73057 rows affected)


SELECT FAMILY_ID FAMILY_IDjoin,FILE_GROUP FILE_GROUPjoin,FMID_HQnew
 INTO #CKFAMHQREGION  FROM ( 
SELECT 
FAMILY_ID,FILE_GROUP,CSG_HQ_ID,CSG_REGION_BCS,SITECNT,ROW_NUMBER() OVER (PARTITION BY FAMILY_ID ORDER BY SITECNT DESC) HQ_ORDER,
CASE WHEN ROW_NUMBER() OVER (PARTITION BY FAMILY_ID ORDER BY SITECNT DESC) = 1 THEN  REPLACE(CSG_REGION_BCS,' REGION','')  ELSE '' END FMID_HQnew
FROM (  
	SELECT FAMILY_ID,FILE_GROUP,CSG_HQ_ID,CSG_REGION_BCS,COUNT(DISTINCT DISTINCT_LOC_ID)  SITECNT
  FROM
    RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO AS A WITH (NOLOCK)
	WHERE FILE_GROUP = 'CSG' AND FAMILY_ID_REGION IN ('UNKNOWN') 
	AND CSG_REGION_BCS IN ('SEATTLE REGION','PORTLAND REGION','CALIFORNIA REGION','MOUNTAIN WEST REGION','HOUSTON REGION','TWIN CITIES REGION') 
	GROUP BY FAMILY_ID,FILE_GROUP,CSG_HQ_ID,CSG_REGION_BCS
) AS F
) AS G WHERE HQ_ORDER =1
ORDER BY FAMILY_ID,FILE_GROUP,SITECNT DESC

UPDATE RptCB.Rpt.SCA_MODULE_STAGE1X_DYAO
SET FAMILY_ID_REGION = FMID_HQnew 
FROM  #CKFAMHQREGION
WHERE FAMILY_ID = FAMILY_IDjoin AND FILE_GROUP = FILE_GROUPjoin


---Correcting some Family IDs... With CSG and SV account names with same name but different family_ids, replace the family_id with the most frequent one


SELECT family_id, CSG_BUSN_NAME, CSG_ACCOUNT
into #same_csg_name
FROM B	
WHERE csg_busn_name in (SELECT csg_busn_name
                   FROM BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT 
                   GROUP BY csg_busn_name
                   HAVING COUNT(distinct family_id) > 1
                  ) and SV_ACCOUNT is NULL
order by CSG_BUSN_NAME


select CSG_BUSN_NAME, family_id
into #winning_csg_family_id
from (select CSG_BUSN_NAME, family_id, count(*) as cnt,
             row_number() over (partition by CSG_BUSN_NAME order by count(*) desc) as seqnum
      from #same_csg_name
      group by CSG_BUSN_NAME, family_id
     ) t
where seqnum = 1
order by CSG_BUSN_NAME;



SELECT family_id, SV_ROOT_ACCOUNT_NAME, SV_ROOT_ACCOUNT, CSG_BUSN_NAME
into #same_sv_name
FROM BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT 
WHERE SV_ROOT_ACCOUNT_NAME in (SELECT SV_ROOT_ACCOUNT_NAME
                   FROM BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT 
                   GROUP BY SV_ROOT_ACCOUNT_NAME
                   HAVING COUNT(distinct family_id) > 1
                  ) 
order by SV_ROOT_ACCOUNT_NAME



select SV_ROOT_ACCOUNT_NAME, family_id
into #winning_sv_family_id
from (select SV_ROOT_ACCOUNT_NAME, family_id,count(*) as cnt,
             row_number() over (partition by SV_ROOT_ACCOUNT_NAME order by count(*) desc) as seqnum
      from #same_sv_name
      group by SV_ROOT_ACCOUNT_NAME, family_id
     ) t
where seqnum = 1
order by SV_ROOT_ACCOUNT_NAME;



update BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT 
set family_id = b.family_id
from #winning_csg_family_id b
where BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT.CSG_BUSN_NAME = b.CSG_BUSN_NAME  and SV_ACCOUNT IS NULL
  ---- 290252


update BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT 
set family_id = b.family_id
from #winning_sv_family_id b
where BI_MIP.dbo.SCA_MODULE_STAGE1X_DYAO_EXPERIMENT.SV_ROOT_ACCOUNT_NAME = b.SV_ROOT_ACCOUNT_NAME  
  ---- 2902

